name: LT_SYNC_BRANCHES

on:
  pull_request:
    types: [closed]
    branches: [ release/** ]

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: start sync branch
      id: sync
      uses: mailz/SyncAction@v1
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        BRANCH: "master"

