name: sync_branch

on:
  push:
    branches: [ release_1 ]
  pull_request:
    branches: [ release_1 ]
  

jobs:

  sync-branches:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.1.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "release_1"
          TO_BRANCH: "master"
