# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  sync-branches:

    runs-on: ubuntu-latest


    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.1.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "release_1"
          TO_BRANCH: "master"
