name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_job:
    
    name: test job
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "test github action"


